# SwiftLint Configuration for Rem
# Production-ready linting rules

disabled_rules:
  - trailing_whitespace
  - line_length  # Too strict for this codebase initially

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - unused_declaration
  - yoda_condition

analyzer_rules:
  - unused_import

# Paths to ignore
excluded:
  - Pods
  - Carthage
  - SQLite.swift
  - ffmpegX
  - .build
  - DerivedData

# Reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"

# Rule configurations
cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

file_length:
  warning: 500
  error: 1200
  ignore_comment_only_lines: true

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - w
    - h
    - db
    - i
    - j
    - k

large_tuple:
  warning: 4
  error: 5

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3

type_body_length:
  warning: 300
  error: 500

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

# Custom rules
custom_rules:
  no_print_statements:
    name: "No Print Statements"
    regex: '^\s*print\s*\('
    message: "Use Logger instead of print() for production code"
    severity: warning

  no_force_unwrap_in_production:
    name: "Avoid Force Unwrapping"
    regex: '(?<!\?)!'
    message: "Avoid force unwrapping. Use guard let or if let instead."
    severity: warning
    match_kinds:
      - identifier

  todo_requires_ticket:
    name: "TODO Requires Ticket"
    regex: '//\s*TODO(?!:?\s*\[)'
    message: "TODOs should reference a ticket number: // TODO: [TICKET-123] Description"
    severity: warning
